packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: false
  sharp: false

catalog:
  "@astrojs/vue": ^6.0.1
  astro: ^6.3.3
  astro-icon: ^1.1.5
  vue: ^3.5.34

ignoredBuiltDependencies:
  - esbuild
  - sharp
